<!--- CREADO: ARAM PICHARDO DURAN --->
<!--- EDITO: ARAM PICHARDO DURAN --->
<!--- FECHA CREA: 01/08/2019 --->
<!--- FECHA ÚLTIMA MOD.: 01/08/2019 --->
<!--- AJAX PARA DETERMINAR SI UN CONTRATO DE OBRA DETERMINADA, CONCURSO ABIERTO, BECA POSDOCTORAL O CÁTEDRA CONACYT SE TRASLAPAN --->

