/* CREADO: ARAM PICHARDO DURÁN */
/* EDITO: ARAM PICHARDO DURÁN */
/* FECHA CREA: 24/01/2022 */
/* FECHA ÚLTIMA MOD.: 24/01/2022 */
/* FUNCIONES JAVA SCRIPT PARA PANTALLAS DE LA SECRETARÍA TÉCNICA DEL CTIC */